# Generated by Django 5.2.4 on 2025-09-05 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True, verbose_name='цитата')),
                ('source', models.CharField(max_length=64, verbose_name='источник')),
                ('weight', models.PositiveIntegerField(default=1, help_text='1–100: чем больше, тем выше шанс выпадения', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='вес')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='лайки')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='дизлайки')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'цитата',
                'verbose_name_plural': 'цитаты',
            },
        ),
    ]
